### ISSUE TITLE
calibration with files get error

### ISSUE THREAD

**Issue by robotcator** [rmccorm4/tensorrt-utils#17]
## Description

RuntimeError: Tried to call pure virtual function "IInt8EntropyCalibrator2_pyimpl::read_calibration_cache"

## Environment
use the docker provided in the readme.

## Steps To Reproduce
python onnx_to_tensorrt.py --onnx resnet50/model.onnx -o resnet50.int8.engine --fp16 --int8 --calibration-data imagenet_calibration/files --max-calibration-size 32

**Comment by robotcator** [comment]
@rmccorm4

**Comment by robotcator** [comment]
it seems that we need to add this code to make it works. The builder.config did not affect the calibrator.
```
builder.int8_calibrator = config.int8_calibrator
```

**Comment by rmccorm4** [comment]
You should be able to do either:

New API (using builder AND builder_config)
```
config.int8_calibrator = ...
builder.build_engine(network, config)
```

or 

Old API (using only builder)
```
builder.int8_calibrator = ...
builder.build_cuda_engine(network)
```

But you shouldn't mix and match the two.
