### ISSUE TITLE
Unnamed Layers in Sample ResNet-50 Cache File

### ISSUE THREAD

**Issue by Hassan313** [rmccorm4/tensorrt-utils#23]
@rmccorm4 Hi Ryan,

You have put a sample resnet50.cache file you in the below link:

https://github.com/rmccorm4/tensorrt-utils/blob/master/int8/calibration/caches/resnet50.cache

There are some unnamed layers at the end of the sample. Why are these layers unnmaed?

gpu_0/pool5_1: 3ec805a6
OC2_DUMMY_0: 3d9942c2
(Unnamed Layer* 174) [Constant]_output: 3996cbd8
(Unnamed Layer* 175) [Constant]_output: 3b64f8bc
(Unnamed Layer* 176) [Matrix Multiply]_output: 3e5b5330
gpu_0/pred_1: 3e526e4b
gpu_0/softmax_1: 3afb76dc

Thank you.

**Comment by rmccorm4** [comment]
Hi Hassan, the reasoning for unnamed layers is likely the same across all models/frameworks: https://github.com/rmccorm4/tensorrt-utils/issues/18#issuecomment-650826000

I don't know too many details on why this happens, but likely just no 1:1 mapping between ops somewhere in the conversion code.

**Comment by Hassan313** [comment]
@rmccorm4 Thank you for your response. Do you know who has the information in NVidia, so I can ask from him/her?

**Comment by rmccorm4** [comment]
Hi @Hassan313 , I would try asking on the NVIDIA Developer forums for TensorRT: https://forums.developer.nvidia.com/c/ai-deep-learning/libraries-sdk/tensorrt
