### ISSUE TITLE
get wrongresult using infer_tensorrr_imagenet.py for multi-batch inference 

### ISSUE THREAD

**Issue by ZuoMeng96** [rmccorm4/tensorrt-utils#26]
## Description

hi rmccorm4! I use your code to add optimization proflie for a Resnet101 onnx model which have a dynamic shape in batchsize, and bulid a int8 engine. But when i do inference with  infer_tensorrt_imagenet.py，i only get correct result with batchsize=1. For other batchsize, i get the most of output probability equal to 0.   

I know that i should add something in runtime code, and follow https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#runtime_dimensions, but i didnt figure it out. Could u show me how to make the multi-batch inference, thank u!

## Environment

**TensorRT Version**: TensorRT 7.2.1
**GPU Type**: P4 
**CUDA Version**: 11.0
**CUDNN Version**: 8.0.5
**Operating System + Version**:  Ubuntu 18.04.5 LTS 
**Python Version (if applicable)**: 3.6.9

## Relevant Files

i add codes to get the input shape with batchsize = 32, 
```python
# Run inference.
context.active_optimization_profile = 3
context_inputshape = context.get_binding_shape(0)            
context.set_binding_shape(0, context_inputshape)
context.execute(batch_size, dbindings)
```

still get the wrong result like this.
Input image: /user/z00590385/imagenet_test_dataset/val/n01728572/ILSVRC2012_val_00003569.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n09246464/ILSVRC2012_val_00024591.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n02009912/ILSVRC2012_val_00024166.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n04399382/ILSVRC2012_val_00025599.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n02948072/ILSVRC2012_val_00007580.JPEG
        Prediction: drake                          Probability: 1.88
        Prediction: sea slug                       Probability: 1.88
        Prediction: sea anemone                    Probability: 1.00
Input image: /user/z00590385/imagenet_test_dataset/val/n04254777/ILSVRC2012_val_00026534.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n07684084/ILSVRC2012_val_00046840.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n02666196/ILSVRC2012_val_00030552.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n03207743/ILSVRC2012_val_00044279.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n03133878/ILSVRC2012_val_00031187.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
Input image: /user/z00590385/imagenet_test_dataset/val/n07715103/ILSVRC2012_val_00032107.JPEG
        Prediction: toilet tissue                  Probability: 0.00
        Prediction: sea urchin                     Probability: 0.00
        Prediction: hog                            Probability: 0.00
.......

**Comment by rmccorm4** [comment]
Hi @ZuoMeng96 ,

Try `context.execute_v2(dbindings)` instead.

If that doesn't work, please try saving your engine to a file and running your engine with `tensorrt-utils/inference/infer.py`. 

ex: `python3 infer.py -e resnet101.engine`

**Comment by ZuoMeng96** [comment]
> Hi @ZuoMeng96 ,
> 
> Try `context.execute_v2(dbindings)` instead.
> 
> If that doesn't work, please try saving your engine to a file and running your engine with `tensorrt-utils/inference/infer.py`.
> 
> ex: `python3 infer.py -e resnet101.engine`

Thanks @rmccorm4 . That infer_tensorrt_imagenet.py didn't handle the different profiles at runtime, if there is only one  profile matched with input it does work.
